! dudon_septimal_2.scl
!
Slendro formed by five 8/7 separated by two commas, Dudon 2009
! (= diatonic scale with two "small semitones" of 77/76 & 233/230)
 12
!
 264/233
 266/233
 304/233
 304/233
 308/233
 352/233
 352/233
 400/233
 402/233
 460/233
 464/233
 2/1
! additionnal keys reproduce the septimal tones differential frequencies
! may also be pertinent for M'buti central-African music
